import { JobStatus } from "./job-status.enum";

export interface JobQueueInterface {
  id: string;

  /**
   * Unique identifier for the combination of ideas.
   * Generated as a SHA-256 hash of sorted, tab-prefixed IDs.
   */
  ideas_src_id: string;

  /**
   * Raw prompt details collected from Google Sheets.
   * Used as input for the prompt generation service.
   */
  prompt_input: string;

  /**
   * Current status of the job in the pipeline.
   */
  status: JobStatus;

  created_at: Date;

  updated_at: Date;

  /**
   * JSON structure containing the final prompt after LLM processing.
   * Null until ms-prompt-generation processes the job.
   */
  generated_prompt: Record<string, unknown> | null;

  /**
   * Number of images to be generated for this prompt.
   */
  desired_image_count: number;

  /**
   * Number of images successfully generated by ComfyUI.
   */
  generated_images_count: number;

  /**
   * Number of images successfully uploaded to storage.
   */
  uploaded_images_count: number;

  /**
   * Number of image uploads that failed.
   */
  failed_uploads_count: number;

  /**
   * Reference ID for the job in ComfyUI.
   */
  comfyui_job_id: string;

  /**
   * Number of times the job has been retried after failure.
   */
  retry_count: number;

  /**
   * Last error message encountered during processing.
   */
  last_error_message: string;

  /**
   * Additional metadata for the job.
   */
  metadata: Record<string, unknown> | null;
}
