name: Publish Package to NPM
description: This workflow publishes the package to NPM when a pull request is merged into the main branch.

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true && vars.PREVENT_PUBLISH != 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          registry-url: "https://registry.npmjs.org/"
      - name: Set up .npmrc
        run: |
          if [ -z "$NPM_PUBLISHER_TOKEN" ]; then
            echo "NPM_PUBLISHER_TOKEN secret is missing!"
            exit 1
          fi
          cp .npmrc.sample .npmrc
          sed -i "s|YOUR_AUTH_TOKEN|$NPM_PUBLISHER_TOKEN|g" .npmrc
        shell: bash
        env:
          NPM_PUBLISHER_TOKEN: ${{ secrets.NPM_PUBLISHER_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish --access ${{ vars.PRIVATE_PUBLISH == 'true' && 'restricted' || 'public' }}
      - name: Get package version
        id: get_version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.PACKAGE_VERSION }}
          name: Release ${{ steps.get_version.outputs.PACKAGE_VERSION }}
          body: "Release of version ${{ steps.get_version.outputs.PACKAGE_VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
